"""jieba userdict management for terminology protection.

Builds a jieba-compatible user dictionary from the terminology table so that
multi-character domain terms survive tokenization intact.

Design Decision 2: userdict is generated by TerminologyTable. Each canonical
form and every variant is registered with a high frequency weight (1000) and
the POS tag "nz" (proper noun) to prevent jieba's default dictionary from
splitting compound terms.

Risk 1 mitigation: jieba.load_userdict accumulates rather than replaces.
We force-clear the internal FREQ dict before reloading on terminology updates.
"""
from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

_USERDICT_PATH = Path(__file__).resolve().parent.parent.parent.parent / "data" / "jieba_userdict.txt"


def _ensure_jieba_imported() -> None:
    import jieba
    jieba.setLogLevel(logging.WARNING)


def build_jieba_userdict_file(
    canonicals_and_variants: list[tuple[str, str]],
    output_path: Path | None = None,
) -> Path:
    """Write a jieba userdict file from a list of (surface, entity_type) pairs.

    Each line: word freq pos
    freq=1000 ensures the term dominates over jieba's default dictionary.
    pos="nz" marks it as a proper noun / domain term.
    """
    _ensure_jieba_imported()
    path = output_path or _USERDICT_PATH
    path.parent.mkdir(parents=True, exist_ok=True)

    seen: set[str] = set()
    lines: list[str] = []
    for surface, _entity_type in canonicals_and_variants:
        s = surface.strip()
        if not s or s in seen:
            continue
        seen.add(s)
        lines.append(f"{s} 1000 nz")

    path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Wrote %d terms to jieba userdict: %s", len(lines), path)
    return path


def reload_jieba_with_terminology(
    canonicals_and_variants: list[tuple[str, str]],
    *,
    clear_existing: bool = True,
) -> None:
    """Clear jieba's custom dictionary and reload from terminology entries.

    Args:
        canonicals_and_variants: List of (surface, entity_type) pairs.
        clear_existing: If True (default), clear jieba's internal FREQ cache
            before loading to prevent stale deleted terms from persisting.
    """
    import jieba

    _ensure_jieba_imported()

    if clear_existing:
        # Risk 1 mitigation: jieba's load_userdict is additive, not replace.
        # We must clear the internal frequency cache before reload to ensure
        # deleted terms don't remain protected.
        _clear_jieba_user_freq()

    path = build_jieba_userdict_file(canonicals_and_variants)
    jieba.load_userdict(str(path))
    logger.info("Reloaded jieba userdict with %d unique terms", len(set(s for s, _ in canonicals_and_variants)))


def _clear_jieba_user_freq() -> None:
    """Clear jieba's internal user frequency cache.

    Uses jieba.dt.FREQ (internal API, pinned jieba version) to remove all
    user-added entries. The built-in dictionary is restored from jieba's
    default cache automatically after clearing.
    """
    import jieba

    try:
        from jieba.dt import FREQ  # type: ignore[attr-defined]
        # Only clear user-added entries; jieba rebuilds defaults from its own dict.
        # We track original entries from the built-in dictionary.
        # Approach: snapshot default dict, clear all, restore default.
        if hasattr(jieba.dt, "DEFAULT_FREQ"):
            default = jieba.dt.DEFAULT_FREQ  # type: ignore[attr-defined]
        else:
            # On some jieba versions DEFAULT_FREQ is not exposed; we just clear
            # and let the built-in dict get picked up again next time.
            default = None

        FREQ.clear()

        if default is not None:
            FREQ.update(default)
    except Exception as exc:
        logger.debug("Could not clear jieba user FREQ (non-critical): %s", exc)


def get_terminology_surfaces(table) -> list[tuple[str, str]]:
    """Extract all (surface, entity_type) pairs from a loaded TerminologyTable."""
    pairs: list[tuple[str, str]] = []
    seen: set[str] = set()
    for entry in table.all_entries():
        surfaces = [entry.canonical, *entry.variants]
        for s in surfaces:
            s = s.strip()
            if s and s not in seen:
                seen.add(s)
                pairs.append((s, str(entry.entity_type)))
    return pairs
